[package]
name = "kurtbuilds_regex"
version = "0.1.0"
edition = "2021"
description = "Wraps the regex library to also provide macros"
license = "MIT"

[lib]
name = "regex"
path = "src/lib.rs"

[dependencies]
regex_inner = { version = "1" , package = "regex" }